package com.foolchen.lib.tracker

internal const val SCREEN_NAME_ALIAS = "\$screen_name_alias"
internal const val SCREEN_NAME = "\$title"
internal const val TITLE = "\$screen_name"
internal const val TIME = "\$time"
internal const val EVENT = "event"
internal const val REFERER_ALIAS = "\$referrer_alias"
internal const val REFERER = "\$referrer"
internal const val PARENT_ALIAS = "\$parent_alias"
internal const val PARENT = "\$parent"
internal const val DISTINCT_ID = "\$distinct_id"
internal const val LIB = "lib"
internal const val PROPERTIES = "properties"
internal const val NETWORK_TYPE = "\$network_type"
internal const val WIFI = "\$wifi"
internal const val CHANNEL = "\$channel"
internal const val RESUME_FROM_BACKGROUND = "\$resume_from_background"
internal const val EVENT_DURATION = "\$event_duration"

// 以下为点击元素用字段
internal const val ELEMENT_TYPE = "\$element_type"
internal const val ELEMENT_CONTENT = "\$element_content"
internal const val ELEMENT_X = "\$element_x"
internal const val ELEMENT_Y = "\$element_y"
